apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-image
          image: nginx

  replicas: 3

  selector:
    matchLabels:
      app: myapp


# kubectl create -f replicaset-definition.yml
# kubectl get replicaset
# kubectl describe replicaset
# kubectl get pods

# update file then run:
# kubectl replace -f replicaset-definition.yml

# or:
#?? kubectl scale --replicas=2 replicaset-definition.yml
# kubectl scale --replicas=2 replicaset myapp-replicaset

# kubectl delete pod myapp-replicaset-4tc2t


# kubectl delete replicaset myapp-replicaset

