apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
    app: myapp
    type: pod
    tier: front-end
spec:
  containers:
    - name: nginx-image
      image: nginx

# kubectl create -f pod-definition.yml
# kubectl get pods -o wide

