apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3

  selector:
    matchLabels:
      app: myapp

# kubectl create -f deployment-definition.yml
# kubectl get deployments
# kubectl get replicaset
# kubectl get pods
# kubectl get all
# kubectl describe deployment

# kubectl rollout status deployment-definition.yml
# kubectl rollout history deployment-definition.yml

## todo ---
# to update - change version of a component (rolling update by default, Recreate is another strategy), then:
# kubectl apply -f deployment-definition.yml
# or for tranient update:
# kubectl set image deployment/myapp-deployment nginx=nginx:1.9.1

# to rollback
# kubectl rollout undo deployment/myapp-deployment


# to deploy without a pod definition file (automatically creates a deployment:
# kubectl run nginx --image=nginx
#
# to delete a deployment:
# kubectl delete deployment myapp-deployment
#
